name: example
version: 0.0.1
description: An absolute bare-bones web app.
#author: john <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  build_web_compilers: any
  build_runner: any
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
